### ISSUE TITLE
Add validations log

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ripple/rippled#2397]
Since there's now a performance log file, it would be also nice to have a log for everything related to validations and consensus (my server's validations + signatures, other validator's votes and signatures...).

**Comment by mvadari** [comment]
@bthomee is this resolved by https://github.com/XRPLF/rippled/pull/5291?

**Comment by bthomee** [comment]
> [@bthomee](https://github.com/bthomee) is this resolved by [#5291](https://github.com/XRPLF/rippled/pull/5291)?

The PR has enabled detailed logging of incoming validations from peers, but not outgoing ones, so this issue is partially fixed.
